parameters:
    saison:
        phases:
            - nom: "Phase 1"
              type: "CHAMPIONNAT"
              date_debut: "01/09/n"
              date_fin: "01/02/n+1"
              duree: 4
              ordre: 0
              close: 0
              poules:
                  - { nom: "Poule A", niveau: "1" }
                  - { nom: "Poule B", niveau: "2" }
                  - { nom: "Poule C", niveau: "3" }
                  - { nom: "Poule D", niveau: "4" }
            - nom: "Phase 2"
              type: "CHAMPIONNAT"
              date_debut: "01/02/n+1"
              date_fin: "01/06/n+1"
              ordre: 1
              close: 0
              poules:
                  - { nom: "Poule A", niveau: "1" }
                  - { nom: "Poule B", niveau: "2" }
                  - { nom: "Poule C", niveau: "3" }
                  - { nom: "Poule D", niveau: "4" }
            - nom: "Phase Finale"
              type: "FINALE"
              date_debut: "01/06/n+1"
              date_fin: "01/08/n+1"
              ordre: 2
              close: 0
              poules:
                  - { nom: "Poule A", niveau: "1" }
                  - { nom: "Poule B", niveau: "2" }
                  - { nom: "Poule C", niveau: "3" }
                  - { nom: "Poule D", niveau: "4" }
